version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=db_lojacons
      - POSTGRES_USER=caperez11
      - POSTGRES_PASSWORD=123456
      - POSTGRES_HOST=127.0.0.1
    ports:
      - '5432:5432'
    volumes:
      - ~/Docker/postgres-data:/var/lib/postgresql/data